# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('due_date', models.DateTimeField(verbose_name='date due')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ToDoStatus'),
        ),
    ]
