# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 02:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20170815_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 16, 2, 12, 52, 378235, tzinfo=utc), null=True, verbose_name='date created'),
        ),
    ]
