# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-16 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20170815_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='date created'),
        ),
    ]
